namespace chsarp_intro
{
    public enum Opcion
    {
        Salir = -1,
        Tipos_de_valor = 1,
        Tipos_de_referencia = 2,
        Jerarquia_de_tipos = 3,
        Nulables = 4,
        Enteros = 5,
        Decimales = 6,
        Fechas = 7,
        Clases_de_usuario = 8,
        Metodos_del_tipo_object = 9,
        Interfaces = 10,
        Strings_definicion = 11,
        Strings_funciones_comunes = 12,
        Casting = 13,
        Manejo_de_excepciones = 14,
        Jerarquia_de_excepciones = 15,
        Arrays = 16,
        ICollections = 17,
        Listas = 18,
        Validation_attribute_Required = 19,
        Validation_attribute_MaxLength = 20,
        Validation_attribute_RegularExpressions = 21,
        Validation_attribute_Range = 22,
        Validation_attribute_Custom = 23,
        Delegates = 24,
        Delegates_Genericos = 25,
        Lambdas = 26,
        Tipos_anonimos = 27,
        Genericos = 28,
        Linq_Consultas = 29,
        Linq_Where = 30,
        Linq_Ordering = 31,
        Linq_Select = 32,
        Extension_Methods = 33,
        Herencia = 34
    }
}
